INSERT INTO dishes (name, kind, extension, description, price, is_actual) VALUES
                                                                              ('Caesar Salad with Grilled Chicken', 'salad', NULL, 'Fresh Caesar salad topped with grilled chicken', 12.99, FALSE),
                                                                              ('Caprese Salad with Fresh Mozzarella and Basil', 'salad', NULL, 'Classic Caprese salad with mozzarella and basil', 10.49, FALSE),
                                                                              ('Garlic Shrimp Skewers', 'starter', NULL, 'Grilled shrimp skewers with garlic butter', 14.99, FALSE),
                                                                              ('Bruschetta with Tomato and Basil', 'starter', NULL, 'Toasted bread topped with tomatoes and basil', 9.99, FALSE),
                                                                              ('Spinach and Artichoke Dip', 'starter', NULL, 'Creamy spinach and artichoke dip served with chips', 11.49, FALSE),
                                                                              ('Grilled Ribeye Steak with Herb Butter', 'main course', NULL, 'Juicy ribeye steak with herb butter', 24.99, FALSE),
                                                                              ('Pan-Seared Salmon with Lemon Butter Sauce', 'main course', NULL, 'Salmon fillet in lemon butter sauce', 21.99, FALSE),
                                                                              ('Vegetarian Stir-Fry with Tofu and Vegetables', 'main course', NULL, 'Stir-fried tofu with fresh vegetables', 15.99, FALSE),
                                                                              ('Chicken Alfredo Pasta', 'main course', NULL, 'Creamy Alfredo pasta with grilled chicken', 18.49, FALSE),
                                                                              ('Lamb Chops with Rosemary and Garlic', 'main course', NULL, 'Tender lamb chops seasoned with rosemary', 29.99, FALSE),
                                                                              ('Garlic Mashed Potatoes', 'side dish', NULL, 'Creamy mashed potatoes with garlic', 6.99, FALSE),
                                                                              ('Steamed Jasmine Rice', 'side dish', NULL, 'Fluffy jasmine rice', 4.99, FALSE),
                                                                              ('Roasted Vegetables with Balsamic Glaze', 'side dish', NULL, 'Seasonal vegetables roasted to perfection', 8.49, FALSE),
                                                                              ('French Fries with Truffle Oil', 'side dish', NULL, 'Crispy fries drizzled with truffle oil', 5.99, FALSE),
                                                                              ('Quinoa Salad with Lemon and Herbs', 'side dish', NULL, 'Healthy quinoa salad with fresh herbs', 7.99, FALSE),
                                                                              ('Chocolate Lava Cake', 'dessert', NULL, 'Decadent chocolate cake with molten center', 9.99, FALSE),
                                                                              ('New York Cheesecake', 'dessert', NULL, 'Classic cheesecake with a graham cracker crust', 8.99, FALSE),
                                                                              ('Tiramisu with Espresso Soak', 'dessert', NULL, 'Layered tiramisu with espresso', 7.49, FALSE),
                                                                              ('Crème Brûlée', 'dessert', NULL, 'Rich custard topped with caramelized sugar', 10.49, FALSE),
                                                                              ('Fresh Fruit Tart with Custard', 'dessert', NULL, 'Delicious tart topped with fresh fruits', 9.49, FALSE),
                                                                              ('Freshly Squeezed Orange Juice', 'beverage', NULL, 'Refreshing orange juice', 3.99, FALSE),
                                                                              ('Iced Matcha Latte', 'beverage', NULL, 'Chilled matcha latte with milk', 4.49, FALSE),
                                                                              ('Classic Lemonade', 'beverage', NULL, 'Sweet and tangy lemonade', 2.99, FALSE),
                                                                              ('Cappuccino with Foamed Milk', 'beverage', NULL, 'Rich cappuccino with foamed milk', 3.99, FALSE),
                                                                              ('Virgin Mojito with Mint and Lime', 'beverage', NULL, 'Refreshing mojito without alcohol', 4.99, FALSE);
